export enum CustomErrorCode {
    // Authentication
    AUTH_MISSING = 'TN_AUTH_100',
    AUTH_INVALID = 'TN_AUTH_101',
    AUTH_EXPIRED = 'TN_AUTH_102',
    AUTH_BLOCKED = 'TN_AUTH_103',
    SESSION_EXPIRED = 'TN_AUTH_104',
    AUTH_DEVICE_ID_MISSING = 'TN_AUTH_105',

    INVALID_USERNAME = 'TN_AUTH_106',

    // Permission
    ACCESS_DENIED = 'TN_PERM_200',
    ACTION_NOT_ALLOWED = 'TN_PERM_201',

    // Validation
    INVALID_INPUT = 'TN_VAL_300',
    FIELD_FORMAT_INVALID = 'TN_VAL_301',
    VALIDATION_ERROR = 'TN_VAL_302',
    DUPLICATE_RESOURCE = 'TN_VAL_303',

    // Resource
    RESOURCE_NOT_FOUND = 'TN_RES_400',
    RESOURCE_EXISTS = 'TN_RES_401',
    RESOURCE_STATE_INVALID = 'TN_RES_402',

    // Database
    DB_WRITE_FAILED = 'TN_DB_500',
    DB_READ_FAILED = 'TN_DB_501',
    DB_CONFLICT = 'TN_DB_502',

    // Bad request
    BAD_REQUEST = 'TN_BR_403',
    UNAUTHORIZED_DEVICE = 'TN_BD_404',

    // System
    INTERNAL_ERROR = 'TN_SYS_600',
    DEPENDENCY_ERROR = 'TN_SYS_601',
    UNSUPPORTED_ACTION = 'TN_SYS_602',

    // Limits
    RATE_LIMIT_EXCEEDED = 'TN_LIM_700',
    QUOTA_EXCEEDED = 'TN_LIM_701',
    TOO_MANY_ATTEMPTS = 'TN_LIM_702',

    // Payments
    PAYMENT_FAILED = 'TN_PAY_800',
    PAYMENT_METHOD_UNSUPPORTED = 'TN_PAY_801',
    REFUND_FAILED = 'TN_PAY_802',

    // External Dependency
    MISSING_DEPENDENCY = 'TN_DEP_900',

    INTERNAL_SERVER_ERROR = 'TN_ISE_901'
}
